### ISSUE TITLE
Obnova hesla

### ISSUE THREAD

**Issue by vendaciki** [div-cz/div_app#82]
jednou na to dojít muselo :-D

**Comment by KuceraMar** [comment]
Ja myslim, ze to funguje.  Akorat to neni viditelny. Ani otestovaný. 

/zapomenute-heslo/

**Comment by KuceraMar** [comment]
https://test.div.cz/accounts/password_reset/

**Comment by vendaciki** [comment]
poslala jsem si reset hesla na e-mail, který není registrovaný, ale reset mi přišel. Neproběhne i nějaká kontrola e-mailu?

**Comment by vendaciki** [comment]
a tady je angličtina

![Snímek obrazovky 2024-12-26 172332](https://github.com/user-attachments/assets/82349cb5-7fe5-404d-8a08-0a264e46cce2)

**Comment by KuceraMar** [comment]
opraveno, odkaz u přilášení
